---
- hosts: all

  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: "Verzeichnis erstellen"
      file:
        path: "{{ docroot }}"
        state: directory
        mode: 0755
    - name: "Webseite kopieren"
      copy:
        src: files/index.html
        dest: {{ docroot }}
        owner: www-data
        group: www-data
        mode: 0644
  roles:
    - { role: ansible-role-apache }
