---
- hosts: all

  vars_files:
    - vars/main.yml
  pre_tasks:
    - file:
        path: "{{ docroot }}"
        state: directory
        mode: 0755
    - copy:
        src: files/index.html
        dest: /var/www/vhosts/example_com
        owner: www-data
        group: www-data
        mode: 0644
  roles:
    - { role: ansible-role-apache }
